// B4RRHH — identidad visual. Generado por tools/identidad/build_all.py; no editar a mano.
// Un nombre por <symbol id="b4-..."> de public/icons/b4-icons.svg.
export const B4_ICON_NAMES = [
  'empleado',
  'empresa',
  'centro-trabajo',
  'centro-coste',
  'catalogo',
  'convenio',
  'recibo',
  'operacion',
  'rule-system',
  'alta',
  'cese',
  'readmision',
  'periodo',
  'nomina',
  'jornada',
  'foto',
  'usuario',
  'buscar',
  'anadir',
  'editar',
  'cerrar',
  'comprobar',
  'imprimir',
  'copiar',
  'mas-opciones',
  'chevron-abajo',
  'flecha-derecha',
  'salir',
  'grafico',
  'documento-nuevo',
  'aviso',
  'informacion',
  'error',
  'detener',
] as const;

export type B4IconName = (typeof B4_ICON_NAMES)[number];
