export const ruleSystemTexts = {
  listTitle: 'Sistemas de reglas',
  listCreateAction: 'Crear sistema de reglas',
  listCodeHeader: 'Código',
  listNameHeader: 'Nombre',
  listCountryHeader: 'País',
  listActiveHeader: 'Activo',
  listOpenAction: 'Abrir',
  listLoadingMessage: 'Cargando sistemas de reglas...',
  listEmptyMessage: 'No hay sistemas de reglas registrados.',
  listRequestFailedMessage: 'No se pudieron cargar los sistemas de reglas',
  activeLabel: 'Sí',
  inactiveLabel: 'No',
  createTitle: 'Nuevo sistema de reglas',
  createSubtitle: 'Alta de un sistema de reglas nuevo.',
  editTitlePrefix: 'Sistema de reglas',
  editLoadingMessage: 'Cargando el sistema de reglas...',
  editRequestFailedMessage: 'No se pudo cargar el sistema de reglas',
  formCodeLabel: 'Código',
  formNameLabel: 'Nombre',
  formCountryCodeLabel: 'País (ISO 3166-1 alpha-3)',
  formActiveLabel: 'Activo',
  formCodeHelp: 'Es la clave del sistema de reglas: no se cambia una vez creado.',
  formSaveCreateAction: 'Crear sistema de reglas',
  formSaveEditAction: 'Guardar cambios',
  formCancelAction: 'Volver',
  formCodeRequiredMessage: 'El código es obligatorio.',
  formCodeMaxLengthMessage: 'El código admite como máximo 5 caracteres.',
  formNameRequiredMessage: 'El nombre es obligatorio.',
  formNameMaxLengthMessage: 'El nombre admite como máximo 100 caracteres.',
  formCountryRequiredMessage: 'El país es obligatorio.',
  formCountryLengthMessage: 'El país son tres letras (ESP, FRA, PRT).',
  saveBusyMessage: 'Guardando cambios...',
  createSuccessMessage: 'Sistema de reglas creado correctamente.',
  updateSuccessMessage: 'Sistema de reglas actualizado correctamente.',
} as const;
