export const ruleSystemTexts = {
  listTitle: 'Rule systems',
  listSubtitle: 'Business maintenance of rule systems for personnel administration.',
  listCreateAction: 'Crear rule system',
  listCodeHeader: 'Code',
  listNameHeader: 'Name',
  listCountryHeader: 'Country',
  listActiveHeader: 'Active',
  listOpenAction: 'Open',
  listLoadingMessage: 'Cargando rule systems...',
  listEmptyMessage: 'No hay rule systems registrados.',
  listRequestFailedMessage: 'No se pudieron cargar los rule systems',
  activeLabel: 'Yes',
  inactiveLabel: 'No',
  createTitle: 'Create rule system',
  createSubtitle: 'Alta de un nuevo rule system por clave de negocio.',
  editTitlePrefix: 'Rule system',
  editLoadingMessage: 'Cargando detalle de rule system...',
  editRequestFailedMessage: 'No se pudo cargar el rule system solicitado',
  formCodeLabel: 'Code',
  formNameLabel: 'Name',
  formCountryCodeLabel: 'Country code',
  formActiveLabel: 'Active',
  formCodeHelp: 'Immutable business key in edit mode.',
  formSaveCreateAction: 'Create rule system',
  formSaveEditAction: 'Save changes',
  formCancelAction: 'Back',
  formCodeRequiredMessage: 'Code is required.',
  formCodeMaxLengthMessage: 'Code must have at most 5 characters.',
  formNameRequiredMessage: 'Name is required.',
  formNameMaxLengthMessage: 'Name must have at most 100 characters.',
  formCountryRequiredMessage: 'Country code is required.',
  formCountryLengthMessage: 'Country code must have exactly 3 characters.',
  saveBusyMessage: 'Guardando cambios...',
  createSuccessMessage: 'Rule system creado correctamente.',
  updateSuccessMessage: 'Rule system actualizado correctamente.',
} as const;
