export const catalogTexts = {
  pageTitle: 'Catálogos',
  pageSubtitle: 'Selecciona un rule system y un tipo para consultar y crear entidades de catalogo.',
  selectorLabel: 'Rule system',
  selectorPlaceholder: 'Selecciona un rule system',
  typePanelTitle: 'Rule entity types',
  entityPanelTitle: 'Rule entities',
  entityPanelSubtitle: 'Listado filtrado por rule system y tipo seleccionado.',
  createPanelTitle: 'Nuevo rule entity',
  createPanelSubtitle: 'Alta en el contexto seleccionado de rule system y type.',
  emptyNoRuleSystem: 'Selecciona un rule system para continuar.',
  emptyNoType: 'Selecciona un rule entity type para ver entidades.',
  emptyNoEntities: 'No entities yet for this context.',
  loadingRuleSystems: 'Cargando rule systems...',
  loadingRuleEntityTypes: 'Cargando rule entity types...',
  loadingRuleEntities: 'Cargando rule entities...',
  listCodeHeader: 'Code',
  listNameHeader: 'Name',
  listActiveHeader: 'Active',
  listStartDateHeader: 'Start date',
  listEndDateHeader: 'End date',
  listActionsHeader: 'Actions',
  activeYes: 'Yes',
  activeNo: 'No',
  actionCorrect: 'Corregir',
  actionClose: 'Cerrar',
  actionDelete: 'Eliminar',
  actionCancel: 'Cancelar',
  createCodeLabel: 'Code',
  createNameLabel: 'Name',
  createDescriptionLabel: 'Description',
  createStartDateLabel: 'Start date',
  createEndDateLabel: 'End date',
  createSubmitAction: 'Crear rule entity',
  createCodeRequired: 'Code is required.',
  createCodeMaxLength: 'Code must have at most 30 characters.',
  createNameRequired: 'Name is required.',
  createNameMaxLength: 'Name must have at most 100 characters.',
  createDescriptionMaxLength: 'Description must have at most 500 characters.',
  createStartDateRequired: 'Start date is required.',
  createEndDateInvalidRange: 'End date must be greater than or equal to start date.',
  operationPanelCorrectTitle: 'Corregir ocurrencia',
  operationPanelCorrectSubtitle:
    'Actualiza nombre, descripción o fecha fin de la ocurrencia seleccionada.',
  operationPanelCloseTitle: 'Cerrar ocurrencia',
  operationPanelCloseSubtitle: 'Indica la fecha de fin para cerrar la ocurrencia vigente.',
  operationPanelDeleteTitle: 'Eliminar ocurrencia',
  operationPanelDeleteSubtitle: 'Esta acción elimina la ocurrencia seleccionada.',
  operationTargetLabel: 'Ocurrencia',
  operationSubmitCorrectAction: 'Guardar corrección',
  operationSubmitCloseAction: 'Confirmar cierre',
  operationConfirmDeleteAction: 'Confirmar eliminación',
  operationDeleteMessage:
    'Confirma la eliminación de esta ocurrencia. Esta acción no se puede deshacer.',
  operationDeletingMessage: 'Eliminando ocurrencia...',
  correctSuccessMessage: 'Rule entity corregida correctamente.',
  closeSuccessMessage: 'Rule entity cerrada correctamente.',
  deleteSuccessMessage: 'Rule entity eliminada correctamente.',
  correctInvalidMessage: 'Completa los datos de corrección con un rango de fechas válido.',
  closeInvalidMessage:
    'La fecha de cierre debe ser válida y mayor o igual al inicio de la ocurrencia.',
  conflictErrorMessagePrefix: 'No se pudo completar la operación por conflicto.',
  conflictGenericErrorMessage:
    'No se pudo completar la operación porque los datos entraron en conflicto.',
  createSuccessMessage: 'Rule entity creada correctamente.',
  genericErrorMessage: 'No se pudo completar la operación. Reintenta.',
  creatingMessage: 'Creando rule entity...',
} as const;
