export const catalogTexts = {
  pageTitle: 'Catálogos',
  pageSubtitle: 'Elige un sistema de reglas y un tipo para ver y crear sus entidades.',
  selectorLabel: 'Sistema de reglas',
  selectorPlaceholder: 'Selecciona un sistema de reglas',
  typePanelTitle: 'Tipos de entidad',
  entityPanelTitle: 'Entidades',
  createPanelTitle: 'Nueva entidad',
  emptyNoRuleSystem: 'Selecciona un sistema de reglas para continuar.',
  emptyNoType: 'Selecciona un tipo de entidad para ver sus entidades.',
  emptyNoEntities: 'Todavía no hay entidades de este tipo.',
  loadingRuleSystems: 'Cargando sistemas de reglas...',
  loadingRuleEntityTypes: 'Cargando tipos de entidad...',
  loadingRuleEntities: 'Cargando entidades...',
  listCodeHeader: 'Código',
  listNameHeader: 'Nombre',
  listActiveHeader: 'Activa',
  listStartDateHeader: 'Inicio',
  listEndDateHeader: 'Fin',
  listActionsHeader: 'Acciones',
  activeYes: 'Sí',
  activeNo: 'No',
  actionCorrect: 'Corregir',
  actionClose: 'Cerrar',
  actionDelete: 'Eliminar',
  actionCancel: 'Cancelar',
  createCodeLabel: 'Código',
  createNameLabel: 'Nombre',
  createDescriptionLabel: 'Descripción',
  createStartDateLabel: 'Fecha de inicio',
  createEndDateLabel: 'Fecha de fin',
  createSubmitAction: 'Crear entidad',
  createCodeRequired: 'El código es obligatorio.',
  createCodeMaxLength: 'El código admite como máximo 30 caracteres.',
  createNameRequired: 'El nombre es obligatorio.',
  createNameMaxLength: 'El nombre admite como máximo 100 caracteres.',
  createDescriptionMaxLength: 'La descripción admite como máximo 500 caracteres.',
  createStartDateRequired: 'La fecha de inicio es obligatoria.',
  createEndDateInvalidRange: 'La fecha de fin no puede ser anterior a la de inicio.',
  operationPanelCorrectTitle: 'Corregir ocurrencia',
  operationPanelCorrectSubtitle:
    'Actualiza nombre, descripción o fecha fin de la ocurrencia seleccionada.',
  operationPanelCloseTitle: 'Cerrar ocurrencia',
  operationPanelCloseSubtitle: 'Indica la fecha de fin para cerrar la ocurrencia vigente.',
  operationPanelDeleteTitle: 'Eliminar ocurrencia',
  operationPanelDeleteSubtitle: 'Esta acción elimina la ocurrencia seleccionada.',
  operationTargetLabel: 'Ocurrencia',
  operationSubmitCorrectAction: 'Guardar corrección',
  operationSubmitCloseAction: 'Confirmar cierre',
  operationConfirmDeleteAction: 'Confirmar eliminación',
  operationDeleteMessage:
    'Confirma la eliminación de esta ocurrencia. Esta acción no se puede deshacer.',
  operationDeletingMessage: 'Eliminando ocurrencia...',
  correctSuccessMessage: 'Entidad corregida correctamente.',
  closeSuccessMessage: 'Entidad cerrada correctamente.',
  deleteSuccessMessage: 'Entidad eliminada correctamente.',
  correctInvalidMessage: 'Completa los datos de corrección con un rango de fechas válido.',
  closeInvalidMessage:
    'La fecha de cierre debe ser válida y mayor o igual al inicio de la ocurrencia.',
  conflictErrorMessagePrefix: 'No se pudo completar la operación por conflicto.',
  conflictGenericErrorMessage:
    'No se pudo completar la operación porque los datos entraron en conflicto.',
  createSuccessMessage: 'Entidad creada correctamente.',
  genericErrorMessage: 'No se pudo completar la operación',
  creatingMessage: 'Creando entidad...',
} as const;
