export const employeeTexts = {
  masterTitle: 'Empleados',
  masterSubtitle: '',
  searchLabel: 'Buscar empleado',
  searchPlaceholder: 'Nombre, apellidos o número',
  openAction: 'Abrir primer resultado',
  resultEmployeesTitle: 'Empleados',
  noResultEmployeesTitle: 'Sin resultados',
  noResultEmployeesDescription: 'No hay empleados que coincidan con la búsqueda.',
  emptyDirectoryTitle: 'Sin empleados',
  emptyDirectoryDescription: 'No hay empleados disponibles.',
  detailPanelTitle: 'Ficha de empleado',
  detailPanelSubtitle: '',
  emptyDetailTitle: 'Selecciona un empleado',
  emptyDetailDescription: 'Abre un empleado desde la lista para ver su ficha.',
  detailIdentityTitle: 'Identidad del empleado',
  detailAvatarPlaceholderAriaLabel: 'Marcador de avatar del empleado',
  detailHeaderRuleSystemLabel: 'Sistema',
  detailHeaderEmployeeTypeLabel: 'Tipo',
  detailHeaderEmployeeNumberLabel: 'Número',
  detailHeaderWorkCenterLabel: 'Centro',
  detailHeaderStatusLabel: 'Estado',
  employeePageHeaderActionsAriaLabel: 'Acciones de la ficha del empleado',
  employeePageHeaderIdentifiersAriaLabel: 'Identificadores del empleado',
  employeePageHeaderContextAriaLabel: 'Contexto del empleado',
  employeePageHeaderContactAriaLabel: 'Información de contacto del empleado',
  employeePageHeaderEditIdentityAction: 'Editar identidad',
  employeePageHeaderTerminateAction: 'Dar de baja',
  employeePageHeaderRehireAction: 'Reactivar',
  globalMessageRailTitle: 'Mensajes',
  globalMessageRailAriaLabel: 'Mensajes globales del empleado',
  globalMessageRailExpandAction: 'Ver mensajes',
  globalMessageRailCollapseAction: 'Ocultar',
  globalMessageRailCloseDetailAction: 'Cerrar detalle',
  globalMessageRailGoToSectionAction: 'Ir a la seccion',
  globalMessageRailErrorsEyebrow: 'Requiere atencion',
  globalMessageRailWarningsEyebrow: 'Revisar',
  globalMessageRailSuccessEyebrow: 'Actualizacion reciente',
  globalMessageRailInfoEyebrow: 'Información',
  globalMessageRailErrorSingular: 'error',
  globalMessageRailErrorPlural: 'errores',
  globalMessageRailWarningSingular: 'advertencia',
  globalMessageRailWarningPlural: 'advertencias',
  globalMessageRailSuccessSingular: 'exito',
  globalMessageRailSuccessPlural: 'exitos',
  globalMessageRailInfoSingular: 'aviso',
  globalMessageRailInfoPlural: 'avisos',
  globalMessageRailAdditionalMessageSingular: 'mensaje más',
  globalMessageRailAdditionalMessagePlural: 'mensajes más',
  terminatePanelTitle: 'Dar de baja',
  terminatePanelTerminationDateLabel: 'Fecha de baja',
  terminatePanelExitReasonLabel: 'Motivo de baja',
  terminatePanelLoadingExitReasonsPlaceholder: 'Cargando motivos de baja...',
  terminatePanelSelectExitReasonPlaceholder: 'Selecciona un motivo de baja',
  terminatePanelEmptyOptionsMessage: 'No hay motivos de baja disponibles para este sistema.',
  terminatePanelCancelAction: 'Cancelar',
  terminatePanelSubmitAction: 'Dar de baja',
  terminatePanelSummaryTitle: 'Resultado de la terminación',
  terminatePanelSummaryDateLabel: 'Fecha',
  terminatePanelSummaryReasonLabel: 'Motivo',
  terminatePanelSummaryStatusLabel: 'Estado',
  terminatePanelSummaryWorkingTimeTitle: 'Jornada cerrada',
  terminatePanelLoadExitReasonsErrorMessage:
    'No se pudieron cargar los motivos de baja. Reintenta.',
  terminatePanelMissingEmployeeKeyMessage: 'Falta la clave del empleado.',
  terminatePanelInvalidPayloadMessage: 'La solicitud no es válida.',
  terminatePanelEmployeeNotFoundMessage: 'No se encontró el empleado o el sistema.',
  terminatePanelConflictMessage: 'Existe un conflicto funcional que impide la baja.',
  terminatePanelBusinessValidationMessage: 'La validación de negocio ha fallado.',
  terminatePanelRequestFailedMessage: 'La solicitud ha fallado.',
  employeePageHeaderCompanyLabel: 'Empresa',
  employeePageHeaderWorkCenterLabel: 'Centro',
  employeePageHeaderHireDateLabel: 'Alta',
  employeePageHeaderEmailLabel: 'Email',
  employeePageHeaderPhoneLabel: 'Teléfono',
  employeePageHeaderEmptyValue: '—',
  employeeStatusActiveLabel: 'Activo',
  employeeStatusInactiveLabel: 'Baja',
  employeeStatusPendingLabel: 'Pendiente',
  detailHeaderEditAction: 'Editar nombre',
  detailHeaderEditPopoverTitle: 'Editar identidad',
  detailHeaderFirstNameLabel: 'Nombre',
  detailHeaderLastName1Label: 'Primer apellido',
  detailHeaderLastName2Label: 'Segundo apellido',
  detailHeaderPreferredNameLabel: 'Nombre preferido',
  detailHeaderSaveAction: 'Guardar',
  detailHeaderCancelAction: 'Cancelar',
  detailHeaderUpdateErrorMessage: 'No se pudo actualizar la identidad del empleado. Reintenta.',
  detailHeaderUpdateSuccessMessage: 'Identidad actualizada correctamente.',
  detailHeaderAvatarFallback: 'NA',
  unknownEmployeeName: 'Empleado externo',
  unknownEmployeeWorkCenter: 'Centro no informado',
  unknownEmployeeStatus: 'Estado no informado',
  detailLoadingMessage: 'Cargando detalle del empleado...',
  detailNotFoundMessage: 'No se encontro detalle para la clave de negocio seleccionada.',
  detailLoadFailedMessage:
    'No se pudo cargar el detalle del empleado. Reintenta navegando de nuevo.',
  directoryLoadingMessage: 'Cargando listado de empleados...',
  directoryLoadFailedMessage: 'No se pudo cargar el listado de empleados. Reintenta.',
  catalogLoadFailedMessage: 'Error al cargar las opciones de catálogo.',
  contactNavLabel: 'Contacto',
  presenceNavLabel: 'Presencia',
  detailAreasNavLabel: 'Áreas del empleado',
  summaryAreaLabel: 'Resumen',
  relationAreaLabel: 'La relación',
  personAreaLabel: 'La persona',
  personalAreaLabel: 'Personales',
  organizationCostCenterAreaLabel: 'Cost center',
  organizationAssignmentAreaLabel: 'Assignment',
  organizationLocationAreaLabel: 'Location',
  organizationDepartmentAreaLabel: 'Department',
  organizationManagerAreaLabel: 'Manager',
  costCenterSectionTitle: 'Centros de coste',
  costCenterSectionSubtitle:
    'Gestiona la distribución del empleado en centros de coste. La suma de porcentajes debe ser menor o igual al 100%.',
  costCenterSectionAddAction: 'Añadir distribución',
  costCenterSectionReplaceAction: 'Sustituir distribución desde fecha',
  costCenterSectionCloseAction: 'Cerrar distribución',
  costCenterSectionCancelAction: 'Cancelar',
  costCenterSectionSaveAction: 'Guardar',
  costCenterSectionConfirmCloseMessage:
    'Confirma el cierre de la distribución activa. Se cerrarán todas las líneas asociadas.',
  costCenterSectionConfirmCloseAction: 'Confirmar cierre',
  costCenterSectionEmptyMessage: 'No hay distribuciones de centros de coste cargadas.',
  costCenterSectionStartDateLabel: 'Fecha inicio',
  costCenterSectionEffectiveDateLabel: 'Fecha efectiva',
  costCenterSectionEndDateLabel: 'Fecha fin',
  costCenterSectionCloseDateLabel: 'Fecha de cierre',
  costCenterSectionTotalLabel: 'Total asignado',
  costCenterSectionAddItemAction: 'Añadir línea',
  costCenterSectionRemoveItemAction: 'Quitar',
  costCenterSectionCodeLabel: 'Centro de coste',
  costCenterSectionPercentageLabel: 'Porcentaje (%)',
  costCenterSectionCurrentStatus: 'Vigente',
  costCenterSectionClosedStatus: 'Histórica',
  costCenterSectionCurrentPeriodLabel: 'actual',
  costCenterSectionHistoryTitle: 'Histórico de distribuciones',
  costCenterSectionInvalidTotalMessage: 'El total de porcentajes no puede superar el 100%.',
  costCenterSectionMinItemsMessage: 'Debe haber al menos una línea de distribución.',
  costCenterSectionRequestFailedMessage: 'Error procesando centros de coste. Reintenta.',
  costCenterSectionCreateSuccessMessage: 'Distribución creada correctamente.',
  costCenterSectionReplaceSuccessMessage: 'Distribución sustituida correctamente.',
  costCenterSectionCloseSuccessMessage: 'Distribución cerrada correctamente.',
  payrollAreaLabel: 'Nómina',
  // --- Acciones de página (en la identidad, ADR-050 §1) ---
  pageActionsAriaLabel: 'Acciones de la ficha',
  // --- La barra de identidad (frontend#24) ---
  identityHireLabel: 'alta',
  identitySeniorityLabel: 'antigüedad',
  identitySeniorityLessThanMonth: 'menos de un mes',
  identityYearLabel: 'año',
  identityYearsLabel: 'años',
  identityMonthLabel: 'mes',
  identityMonthsLabel: 'meses',
  identityAndLabel: 'y',
  identityCopyMatriculaAction: 'Copiar matrícula',
  identityChangePhotoAction: 'Cambiar foto del empleado',
  identityDeletePhotoAction: 'Eliminar foto',
  identityPhotoAlt: 'Foto del empleado',
  pageActionsMenuLabel: 'Acciones',
  pageActionsLifecycleGroup: 'Ciclo de vida',
  pageActionCalculatePayroll: 'Calcular nómina',
  pageActionTerminate: 'Iniciar cese',
  pageActionRehire: 'Recontratación',
  pageActionChangeWorkCenter: 'Cambiar centro de trabajo',
  pageActionNewContract: 'Nuevo contrato',
  pageActionSalaryReview: 'Registrar revisión salarial',
  areaDisabledLabel: 'Disponible en siguiente iteracion',
  navRoutingHint:
    'Personales, Laborales y Organizativos ya navegan sobre verticales activos. Nómina queda preparada.',
  payrollInputsSectionTitle: 'Entradas de nómina',
  payrollInputsSectionSubtitle:
    'Cantidades de entrada por período que consume el motor de cálculo.',
  payrollInputsPeriodLabel: 'Período',
  payrollInputsPrevPeriodAriaLabel: 'Período anterior',
  payrollInputsNextPeriodAriaLabel: 'Período siguiente',
  payrollInputsConceptCodeLabel: 'Concepto',
  payrollInputsConceptCodePlaceholder: 'Ej: HE_QTY',
  payrollInputsQuantityLabel: 'Cantidad',
  payrollInputsQuantityPlaceholder: '0',
  payrollInputsAddAction: 'Añadir entrada',
  payrollInputsEditAction: 'Editar',
  payrollInputsDeleteAction: 'Eliminar',
  payrollInputsCancelAction: 'Cancelar',
  payrollInputsSaveCreateAction: 'Guardar',
  payrollInputsSaveEditAction: 'Guardar',
  payrollInputsConfirmDeleteMessage: 'Confirma la eliminación de esta entrada de nómina.',
  payrollInputsConfirmDeleteAction: 'Confirmar eliminación',
  payrollInputsEmptyMessage: 'No hay entradas de nómina para este período.',
  payrollInputsLoadFailedMessage: 'No se pudieron cargar las entradas de nómina.',
  payrollInputsRequestFailedMessage: 'No se pudo procesar la operación. Reintenta.',
  payrollInputsDuplicateMessage: 'Ya existe una entrada para ese concepto y período.',
  payrollInputsNotFoundMessage: 'No se encontro la entrada seleccionada.',
  payrollInputsCreateSuccessMessage: 'Entrada creada correctamente.',
  payrollInputsEditSuccessMessage: 'Entrada actualizada correctamente.',
  payrollInputsDeleteSuccessMessage: 'Entrada eliminada correctamente.',
  payrollAreaLoadingMessage: 'Cargando entradas de nómina...',
  timelineTitle: 'Historial',
  // --- La tira «Hoy» (frontend#25) ---
  todayTitle: 'Hoy',
  todaySinceLabel: 'desde',
  todayHoursPerDayLabel: 'h/día',
  todayAllocatedLabel: 'asignado',
  todayNoneLabel: 'sin vigencia',
  todayUnassignedLabel: 'sin asignar',
  todayGoToLaneAction: 'Ir al carril',
  // --- La línea de vida (frontend#17) ---
  lifelineTitle: 'Línea de vida',
  lifelineLoadingMessage: 'Cargando la línea de vida…',
  lifelineEmptyMessage: 'Todavía no hay vigencias que dibujar.',
  lifelineStageSingularLabel: 'etapa',
  lifelineStagePluralLabel: 'etapas',
  lifelineCompressedScaleLabel: 'escala comprimida',
  lifelineLanePresence: 'Presencia',
  lifelineLaneContract: 'Contrato',
  lifelineLaneWorkingTime: 'Jornada',
  lifelineLaneClassification: 'Convenio',
  lifelineLaneWorkCenter: 'Centro',
  lifelinePresenceLabelPrefix: 'periodo',
  lifelineHoursPerWeekLabel: 'h/semana',
  lifelineContributionGroupLabel: 'grupo',
  lifelineHireLabel: 'Alta',
  lifelineTerminationLabel: 'Cese',
  lifelineRehireLabel: 'Readmisión',
  lifelineTodayLabel: 'Hoy',
  lifelineOpenLabel: 'en vigor',
  lifelineOverlapLabel: 'solape',
  lifelineBreakLabel: 'Interrupción',
  lifelineDayLabel: 'día',
  lifelineDaysLabel: 'días',
  railToggleLabel: 'Plegar o desplegar el panel del empleado',
  timelineEventsSingularLabel: 'evento',
  timelineEventsPluralLabel: 'eventos',
  timelineLastEventLabel: 'Último',
  timelineExpandActionLabel: 'Expandir historial',
  timelineCollapseActionLabel: 'Contraer historial',
  timelineCurrentPeriodLabel: 'vigente',
  timelineCurrentPresenceLabel: 'Vigente',
  timelineClosedPresenceLabel: 'Cerrado',
  timelineEventHireLabel: 'Alta',
  timelineEventRehireLabel: 'Reactivación',
  timelineEventTerminationLabel: 'Baja',
  timelineEventPresenceStartLabel: 'Inicio de periodo',
  timelineEventPresenceEndLabel: 'Fin de periodo',
  timelineEventContractStartLabel: 'Inicio de contrato',
  timelineEventContractChangeLabel: 'Cambio de contrato',
  timelineEventContractEndLabel: 'Fin de contrato',
  timelineEventLaborClassificationStartLabel: 'Inicio de clasificación',
  timelineEventLaborClassificationChangeLabel: 'Cambio de clasificación',
  timelineEventLaborClassificationEndLabel: 'Fin de clasificación',
  timelineEventWorkCenterStartLabel: 'Centro asignado',
  timelineEventWorkCenterEndLabel: 'Fin de asignación de centro',
  timelineNoCompanyLabel: 'Sin empresa',
  timelineStatusCompletedLabel: 'Completado',
  timelineStatusCurrentLabel: 'Actual',
  timelineStatusFutureLabel: 'Futuro',
  timelineNoEventsMessage: 'No hay eventos disponibles.',
  timelineLoadingMessage: 'Cargando journey del empleado...',
  timelineLoadFailedMessage: 'No se pudo cargar el journey del empleado.',
  sectionShellCreateAction: 'Crear',
  sectionShellEditAction: 'Editar',
  sectionShellCancelAction: 'Cancelar',
  sectionShellBusyMessage: 'Procesando cambios...',
  sectionDemoTitle: 'Seccion editable (demo)',
  sectionDemoSubtitle: 'Patron base para separar estado local de UI y datos remotos.',
  sectionDemoViewMessage: 'Estado de lectura. Usa Crear o Editar para abrir modo de trabajo local.',
  sectionDemoCreatingMessage:
    'Modo creating. Simula la captura de un nuevo registro sin backend real.',
  sectionDemoEditingMessage: 'Modo editing. Simula cambios locales antes de confirmar envio.',
  sectionDemoConfirmingMessage:
    'Modo confirming. Punto intermedio antes de ejecutar una acción destructiva.',
  sectionDemoSubmitCreateAction: 'Simular submitCreate()',
  sectionDemoSubmitEditAction: 'Simular submitEdit()',
  sectionDemoConfirmCloseAction: 'Simular confirmClose()',
  sectionDemoCreateSuccessMessage: 'Demo: alta simulada completada.',
  sectionDemoEditSuccessMessage: 'Demo: edición simulada completada.',
  sectionDemoDeleteSuccessMessage: 'Demo: baja simulada completada.',
  sectionDemoCloseSuccessMessage: 'Demo: cierre simulado completado.',
  slotDemoTitle: 'Contactos por slot (demo)',
  slotDemoSubtitle:
    'Patron reusable para alta, edición y baja por fila con una sola operación activa.',
  slotManageAction: 'Gestionar',
  slotExitManageAction: 'Salir de gestión',
  slotAddAction: 'Añadir',
  slotEditAction: 'Editar',
  slotDeleteAction: 'Eliminar',
  slotCancelAction: 'Cancelar',
  slotSaveCreateAction: 'Guardar alta',
  slotSaveEditAction: 'Guardar cambios',
  slotConfirmDeleteMessage: 'Confirma la baja de este registro.',
  slotConfirmDeleteAction: 'Confirmar baja',
  slotEmptyMessage: 'No hay registros cargados.',
  slotKeyFieldLabel: 'Tipo',
  slotValueFieldLabel: 'Valor',
  slotDuplicateKeyErrorMessage: 'No se puede repetir un tipo ya existente.',
  slotCreateSuccessMessage: 'Demo slot: alta simulada completada.',
  slotEditSuccessMessage: 'Demo slot: edición simulada completada.',
  slotDeleteSuccessMessage: 'Demo slot: baja simulada completada.',
  overviewPanelTitle: 'Resumen del empleado',
  overviewPanelSubtitle: '',
  contactPanelTitle: 'Contacto',
  contactPanelSubtitle: '',
  presencePanelTitle: 'Presencia',
  presencePanelSubtitle: '',
  summaryAreaTitle: 'Resumen general',
  summaryAreaSubtitle: 'Contexto administrativo rapido de la ficha.',
  summaryProfileBlockTitle: 'Identidad funcional',
  summaryProfileBlockDescription:
    'Clave de negocio activa y estado de lectura actual para iniciar navegación segura.',
  summaryLifecycleBlockTitle: 'Hitos laborales',
  summaryLifecycleBlockDescription:
    'Esta zona consolidara altas, cambios y cierres en cuanto exista timeline agregado de backend.',
  summaryPendingBlockTitle: 'Proximos pasos',
  summaryPendingBlockDescription:
    'Preparado para alertas operativas: datos incompletos, revisiones y validaciones pendientes.',
  personalContactsBlockTitle: 'Contactos',
  personalContactsBlockDescription:
    'Espacio para teléfono, email y medios principales de contacto del empleado.',
  contactBlockTitle: 'Contactos',
  contactBlockSubtitle: 'Medios principales de contacto del empleado.',
  contactBlockPrimaryPhoneLabel: 'Teléfono principal',
  contactBlockPrimaryEmailLabel: 'Email principal',
  contactBlockSecondaryTitle: 'Otros contactos',
  contactBlockCopyAction: 'Copiar',
  contactBlockEmptyMessage: 'No hay información de contacto disponible.',
  contactBlockTypePhone: 'Teléfono',
  contactBlockTypeEmail: 'Email',
  contactBlockTypeOther: 'Otro',
  contactsSectionTitle: 'Contactos',
  contactsSectionAddAction: 'Añadir contacto',
  contactsSectionEditAction: 'Editar',
  contactsSectionDeleteAction: 'Eliminar',
  contactsSectionCancelAction: 'Cancelar',
  contactsSectionSaveCreateAction: 'Guardar',
  contactsSectionSaveEditAction: 'Guardar',
  contactsSectionConfirmDeleteMessage: 'Confirma la eliminación de este contacto.',
  contactsSectionConfirmDeleteAction: 'Confirmar eliminación',
  contactsSectionEmptyMessage:
    'Sin contactos: ni teléfono ni correo. Añade el primero con «Añadir contacto».',
  contactsSectionListAriaLabel: 'Listado de contactos del empleado',
  contactsSectionKeyFieldLabel: 'Tipo de contacto',
  contactsSectionValueFieldLabel: 'Valor de contacto',
  contactsSectionRequestFailedMessage: 'No se pudo procesar la operación de contactos. Reintenta.',
  contactsSectionDuplicateTypeMessage: 'Ya existe un contacto para ese tipo.',
  contactsSectionCreateSuccessMessage: 'Contacto creado correctamente.',
  contactsSectionEditSuccessMessage: 'Contacto actualizado correctamente.',
  contactsSectionDeleteSuccessMessage: 'Contacto eliminado correctamente.',
  identifiersSectionTitle: 'Identificadores',
  identifiersSectionAddAction: 'Añadir identificador',
  identifiersSectionEditAction: 'Editar',
  identifiersSectionDeleteAction: 'Eliminar',
  identifiersSectionCancelAction: 'Cancelar',
  identifiersSectionSaveCreateAction: 'Guardar',
  identifiersSectionSaveEditAction: 'Guardar',
  identifiersSectionConfirmDeleteMessage: 'Confirma la eliminación de este identificador.',
  identifiersSectionConfirmDeleteAction: 'Confirmar eliminación',
  identifiersSectionEmptyMessage:
    'Sin identificadores: ni DNI ni NIE. Añade el primero con «Añadir identificador».',
  identifiersSectionListAriaLabel: 'Listado de identificadores del empleado',
  identifiersSectionKeyFieldLabel: 'Tipo de identificador',
  identifiersSectionValueFieldLabel: 'Valor del identificador',
  identifiersSectionIssuingCountryLabel: 'País emisor',
  identifiersSectionExpirationDateLabel: 'Fecha de caducidad',
  identifiersSectionIsPrimaryLabel: 'Identificador principal',
  identifiersSectionRequestFailedMessage:
    'No se pudo procesar la operación de identificadores. Reintenta.',
  identifiersSectionDuplicateTypeMessage: 'Ya existe un identificador para ese tipo.',
  identifiersSectionInvalidDniMessage: 'DNI no válido',
  identifiersSectionPrimaryBadge: 'Principal',
  identifiersSectionExpirationPrefix: 'Caduca',
  identifiersSectionCreateSuccessMessage: 'Identificador creado correctamente.',
  identifiersSectionEditSuccessMessage: 'Identificador actualizado correctamente.',
  identifiersSectionDeleteSuccessMessage: 'Identificador eliminado correctamente.',
  personalLoadingMessage: 'Cargando datos personales...',
  contactLoadingMessage: 'Cargando información de contacto...',
  contactLoadFailedMessage: 'No se pudo cargar la información de contacto.',
  contactBlockPlaceholderNote:
    'Información mostrada en modo placeholder hasta disponer de lectura OpenAPI para contactos.',
  personalAddressesBlockTitle: 'Direcciones',
  addressBlockPrimaryLabel: 'Dirección principal',
  addressBlockSecondaryTitle: 'Otras direcciones',
  addressBlockEmptyMessage: 'No hay información de direcciones disponible.',
  addressLoadingMessage: 'Cargando información de direcciones...',
  addressLoadFailedMessage: 'No se pudo cargar la información de direcciones.',
  addressesSectionTitle: 'Direcciones',
  addressesSectionAddAction: 'Añadir dirección',
  addressesSectionEditCurrentAction: 'Corregir dirección vigente',
  addressesSectionCloseAction: 'Cerrar dirección',
  addressesSectionCloseTitle: 'Cerrar dirección',
  addressesSectionSaveCreateAction: 'Guardar',
  addressesSectionSaveEditCurrentAction: 'Guardar corrección',
  addressesSectionConfirmCloseAction: 'Confirmar cierre',
  addressesSectionEmptyMessage: 'Sin direcciones. Añade la primera con «Añadir dirección».',
  addressesSectionRequestFailedMessage:
    'No se pudo procesar la operación de direcciones. Reintenta.',
  addressesSectionCreateSuccessMessage: 'Dirección creada correctamente.',
  addressesSectionEditCurrentSuccessMessage: 'Dirección corregida correctamente.',
  addressesSectionCloseSuccessMessage: 'Dirección cerrada correctamente.',
  addressesSectionEditCurrentHint:
    'Se corrigen los datos de la dirección vigente. Si la persona se ha mudado, ciérrala y añade la nueva.',
  addressesSectionTypeLabel: 'Tipo de dirección',
  addressesSectionAddressColumn: 'Dirección',
  addressesSectionStreetLabel: 'Calle',
  addressesSectionCityLabel: 'Ciudad',
  addressesSectionCountryLabel: 'País',
  addressesSectionPostalCodeLabel: 'Código postal',
  addressesSectionRegionLabel: 'Región',
  addressesSectionStartDateLabel: 'Fecha de inicio',
  addressesSectionEndDateLabel: 'Fecha de fin',
  workCenterSectionTitle: 'Centro de trabajo',
  workCenterSectionSubtitle:
    'Gestiona la asignación vigente y el histórico de centros de trabajo. Permite alta, cierre y corrección administrativa de ocurrencias.',
  workCenterSectionManageAction: 'Administrar asignaciones',
  workCenterSectionExitManageAction: 'Salir',
  workCenterSectionAddAction: 'Añadir asignación',
  workCenterSectionCorrectAction: 'Corregir ocurrencia',
  workCenterSectionCloseAction: 'Cerrar',
  workCenterSectionDeleteAction: 'Eliminar',
  workCenterSectionCancelAction: 'Cancelar',
  workCenterSectionSaveCreateAction: 'Guardar',
  workCenterSectionSaveCorrectAction: 'Guardar corrección',
  workCenterSectionConfirmCloseMessage: 'Confirma el cierre de esta asignación.',
  workCenterSectionConfirmCloseAction: 'Confirmar cierre',
  workCenterSectionConfirmDeleteMessage:
    'Vas a eliminar esta asignación de centro de trabajo. Esta acción no se puede deshacer.',
  workCenterSectionConfirmDeleteAction: 'Confirmar eliminación',
  workCenterSectionEmptyMessage: 'No hay asignaciones de centro de trabajo cargadas.',
  workCenterSectionRequestFailedMessage:
    'No se pudo procesar la operación de centro de trabajo. Reintenta.',
  workCenterSectionOverlapMessage:
    'La asignación se solapa con otra ocurrencia vigente o histórica para este empleado.',
  workCenterSectionOutsidePresenceMessage:
    'El período de centro de trabajo debe estar dentro de un período de presencia del empleado.',
  workCenterSectionCatalogNotFoundMessage:
    'El centro de trabajo indicado no existe en el catalogo disponible.',
  workCenterSectionNotFoundMessage:
    'No se encontro la asignación seleccionada de centro de trabajo.',
  workCenterSectionAlreadyClosedMessage:
    'La asignación ya esta cerrada y no admite un nuevo cierre.',
  workCenterSectionFunctionalInvalidPeriodMessage:
    'El período informado no es válido para esta operación de centro de trabajo.',
  workCenterSectionDeleteForbiddenAtPresenceStartMessage:
    'No se puede eliminar esta asignación porque inicia una presence del empleado. Corrigela si necesitas cambiarla.',
  workCenterSectionDeleteDisabledPresenceStartReason:
    'No eliminable: inicia una presence del empleado. Usa Corregir ocurrencia.',
  workCenterSectionLoadFailedMessage: 'No se pudo cargar la información de centro de trabajo.',
  workCenterSectionCreateSuccessMessage: 'Asignación creada correctamente.',
  workCenterSectionCorrectSuccessMessage: 'Asignación corregida correctamente.',
  workCenterSectionCloseSuccessMessage: 'Asignación cerrada correctamente.',
  workCenterSectionDeleteSuccessMessage: 'Asignación eliminada correctamente.',
  workCenterSectionInvalidPeriodMessage:
    'El período es invalido. La fecha fin no puede ser anterior a la fecha inicio.',
  workCenterSectionCloseDateInvalidMessage:
    'La fecha de cierre debe ser igual o posterior a la fecha de inicio de la asignación.',
  workCenterSectionCurrentStatus: 'Vigente',
  workCenterSectionClosedStatus: 'Histórica',
  workCenterSectionCurrentPeriodLabel: 'actual',
  workCenterSectionPeriodPrefix: 'Período',
  workCenterSectionAssignmentPrefix: 'Asignación',
  workCenterSectionAssignmentLabel: 'Número de asignación',
  workCenterSectionCorrectionHint:
    'Corrigiendo la ocurrencia seleccionada sin crear una nueva asignación.',
  workCenterSectionCloseHint:
    'Define la fecha de cierre para finalizar la vigencia de la asignación actual.',
  workCenterSectionCodeLabel: 'Centro de trabajo',
  workCenterSectionStartDateLabel: 'Fecha inicio',
  workCenterSectionEndDateLabel: 'Fecha fin',
  workCenterSectionCloseDateLabel: 'Fecha de cierre',
  personalIdentifiersBlockTitle: 'Identificadores',
  identifierBlockPrimaryLabel: 'Identificador principal',
  identifierBlockSecondaryTitle: 'Otros identificadores',
  identifierBlockEmptyMessage: 'No hay identificadores disponibles.',
  identifierLoadFailedMessage: 'No se pudo cargar la información de identificadores.',
  identifierBlockIssuingCountryLabel: 'País emisor',
  identifierBlockExpirationDateLabel: 'Expira',
  personalAddressesBlockDescription:
    'Bloque preparado para dirección principal, histórico y vigencias.',
  laborAreaTitle: 'Laborales',
  laborAreaSubtitle:
    'Bloques vinculados a presencia, condicion contractual, jornada y clasificación laboral.',
  laborLoadingMessage: 'Cargando datos laborales...',
  organizationLoadingMessage: 'Cargando datos organizativos...',
  organizationFutureTitle: 'Proximas asignaciones organizativas',
  organizationFutureDescription:
    'Este bloque prepara la incorporación progresiva de cost center, assignment y otras asignaciones organizativas.',
  laborPresenceBlockTitle: 'Presence',
  laborPresenceBlockDescription:
    'Area conectada al vertical de presencia con capacidad de historial y estado activo.',
  presenceBlockTitle: 'Presencia',
  presenceBlockCurrentLabel: 'Presencia actual',
  presenceBlockCurrentActiveSectionLabel: 'Presencia activa',
  presenceBlockCurrentSectionLabel: 'Presencia actual',
  presenceBlockCurrentActiveLabel: 'Presencia activa actual.',
  presenceBlockCurrentActiveMostRecentLabel:
    'Hay varias presencias activas; se muestra la más reciente.',
  presenceBlockCurrentLatestClosedLabel:
    'No hay presencia activa; se muestra la última presencia registrada.',
  presenceBlockHistoryTitle: 'Historial de presencias',
  presenceBlockHistoryEmptyMessage: 'Sin períodos anteriores registrados.',
  presenceBlockEmptyMessage: 'No hay presencias disponibles.',
  presenceLoadFailedMessage: 'No se pudo cargar la información de presencia.',
  presenceBlockStatusActive: 'Activa',
  presenceBlockStatusClosed: 'Cerrada',
  presenceBlockPeriodLabel: 'Período',
  presenceBlockPeriodNumberPrefix: 'período',
  presenceBlockOpenPeriodLabel: 'actual',
  presenceBlockCompanyLabel: 'Empresa',
  presenceBlockEntryReasonLabel: 'Motivo entrada',
  presenceBlockExitReasonLabel: 'Motivo salida',
  laborContractBlockTitle: 'Contract',
  laborContractBlockDescription:
    'Bloque reservado para tipo contractual, fechas clave y cambios vigentes.',
  contractBlockTitle: 'Contrato',
  contractBlockCurrentLabel: 'Contrato actual',
  contractBlockCurrentActiveSectionLabel: 'Contrato activo',
  contractBlockCurrentSectionLabel: 'Contrato actual',
  contractBlockCurrentActiveLabel: 'Contrato activo actual.',
  contractBlockCurrentActiveMostRecentLabel:
    'Hay varios contratos activos; se muestra el más reciente.',
  contractBlockCurrentLatestClosedLabel:
    'No hay contrato activo; se muestra el último contrato registrado.',
  contractBlockHistoryTitle: 'Historial de contratos',
  contractBlockHistoryEmptyMessage: 'Sin períodos contractuales anteriores registrados.',
  contractBlockEmptyMessage: 'No hay contratos disponibles.',
  contractLoadFailedMessage: 'No se pudo cargar la información de contrato.',
  contractBlockStatusActive: 'Activo',
  contractBlockStatusClosed: 'Cerrado',
  contractBlockPeriodLabel: 'Período',
  contractBlockOpenPeriodLabel: 'actual',
  contractSectionTitle: 'Contrato',
  contractSectionSubtitle: 'Gestiona el contrato vigente y su histórico.',
  contractSectionManageAction: 'Cambiar contrato desde fecha',
  contractSectionExitManageAction: 'Salir',
  contractSectionReplaceAction: 'Cambiar contrato desde fecha',
  contractSectionCorrectAction: 'Corregir ocurrencia',
  contractSectionCloseAction: 'Cerrar',
  contractSectionDeleteAction: 'Eliminar',
  contractSectionCancelAction: 'Cancelar',
  contractSectionSaveReplaceAction: 'Guardar reemplazo',
  contractSectionSaveCorrectAction: 'Guardar corrección',
  contractSectionConfirmCloseMessage: 'Confirma el cierre de esta ocurrencia de contrato.',
  contractSectionConfirmCloseAction: 'Confirmar cierre',
  contractSectionConfirmDeleteMessage: 'La eliminación no esta habilitada para contrato.',
  contractSectionConfirmDeleteAction: 'Confirmar eliminación',
  contractSectionEmptyMessage: 'No hay contratos cargados.',
  contractSectionStatusActive: 'Vigente',
  contractSectionStatusClosed: 'Histórico',
  contractSectionCurrentPeriodLabel: 'actual',
  contractSectionPeriodPrefix: 'Período',
  contractSectionSubtypePrefix: 'Subtipo',
  contractSectionEffectiveDateLabel: 'Fecha efectiva',
  contractSectionContractLabel: 'Contrato',
  contractSectionContractPlaceholder: 'Código de contrato',
  contractSectionSubtypeLabel: 'Subtipo',
  contractSectionSubtypePlaceholder: 'Código de subtipo',
  contractSectionOccurrenceStartDateLabel: 'Inicio',
  contractSectionCloseHint: 'Indica la fecha de cierre para finalizar la ocurrencia vigente.',
  contractSectionCloseDateLabel: 'Fecha de cierre',
  contractSectionInvalidDataMessage: 'Completa los datos obligatorios para continuar.',
  contractSectionCloseDateInvalidMessage:
    'La fecha de cierre debe ser igual o posterior al inicio de la ocurrencia.',
  contractSectionRequestFailedMessage: 'No se pudo procesar la operación de contrato. Reintenta.',
  contractSectionReplaceSuccessMessage: 'Contrato reemplazado correctamente.',
  contractSectionCorrectSuccessMessage: 'Contrato corregido correctamente.',
  contractSectionCloseSuccessMessage: 'Contrato cerrado correctamente.',
  workingTimeSectionTitle: 'Jornada',
  workingTimeSectionSubtitle: 'Gestiona la jornada actual y su histórico dentro del area laboral.',
  workingTimeSectionManageAction: 'Nueva jornada',
  workingTimeSectionExitManageAction: 'Salir',
  workingTimeSectionAddAction: 'Nueva jornada',
  workingTimeSectionEditCurrentAction: 'Editar',
  workingTimeSectionCorrectAction: 'Corregir',
  workingTimeSectionCloseAction: 'Cerrar',
  workingTimeSectionDeleteAction: 'Eliminar',
  workingTimeSectionCancelAction: 'Cancelar',
  workingTimeSectionSaveCreateAction: 'Guardar jornada',
  workingTimeSectionSaveEditCurrentAction: 'Guardar',
  workingTimeSectionSaveCorrectAction: 'Guardar',
  workingTimeSectionConfirmCloseMessage: 'Confirma el cierre de esta jornada.',
  workingTimeSectionConfirmCloseAction: 'Confirmar cierre',
  workingTimeSectionConfirmDeleteMessage: 'La eliminación no esta habilitada para jornada.',
  workingTimeSectionConfirmDeleteAction: 'Confirmar eliminación',
  workingTimeSectionEmptyMessage: 'No hay jornadas cargadas.',
  workingTimeSectionStatusActive: 'Actual',
  workingTimeSectionStatusClosed: 'Histórica',
  workingTimeSectionCurrentPeriodLabel: 'actual',
  workingTimeSectionPeriodPrefix: 'Período',
  workingTimeSectionPercentageLabel: 'Porcentaje de jornada',
  workingTimeSectionPercentagePlaceholder: 'Porcentaje',
  workingTimeSectionWeeklyHoursLabel: 'Horas semanales',
  workingTimeSectionDailyHoursLabel: 'Horas diarias',
  workingTimeSectionMonthlyHoursLabel: 'Horas mensuales',
  workingTimeSectionStartDateLabel: 'Fecha inicio',
  workingTimeSectionCloseDateLabel: 'Fecha fin',
  workingTimeSectionDerivedHint:
    'Las horas semanales, diarias y mensuales se calculan automaticamente por el sistema y se muestran solo en lectura.',
  workingTimeSectionCloseHint:
    'Indica la fecha fin para cerrar la jornada vigente sin modificar el histórico anterior.',
  workingTimeSectionInvalidDataMessage:
    'Completa la fecha inicio y un porcentaje de jornada válido para continuar.',
  workingTimeSectionCloseDateInvalidMessage:
    'La fecha fin debe ser igual o posterior a la fecha inicio de la jornada.',
  workingTimeSectionInvalidPercentageMessage:
    'El porcentaje de jornada debe ser mayor que 0 y menor o igual que 100.',
  workingTimeSectionInvalidPeriodMessage:
    'El período informado no es válido para esta operación de jornada.',
  workingTimeSectionOverlapMessage:
    'La jornada se solapa con otra ocurrencia vigente o histórica del empleado.',
  workingTimeSectionOutsidePresenceMessage:
    'La jornada debe quedar dentro de un período de presencia del empleado.',
  workingTimeSectionAlreadyClosedMessage:
    'La jornada ya estaba cerrada y no admite un nuevo cierre.',
  workingTimeSectionNotFoundMessage: 'No se encontro la jornada seleccionada para este empleado.',
  workingTimeSectionNumberConflictMessage:
    'Se ha producido un conflicto de numeracion funcional al crear la jornada. Reintenta.',
  workingTimeSectionRequestFailedMessage: 'No se pudo procesar la operación de jornada. Reintenta.',
  workingTimeSectionCreateSuccessMessage: 'Jornada creada correctamente.',
  workingTimeSectionCloseSuccessMessage: 'Jornada cerrada correctamente.',
  workingTimeSectionUpdateSuccessMessage: 'Jornada actualizada correctamente.',
  workingTimeSectionDeleteSuccessMessage: 'Jornada eliminada correctamente.',
  workingTimeSectionAddTitle: 'Añadir jornada',
  workingTimeSectionCorrectTitle: 'Corregir jornada',
  workingTimeSectionRemoveTitle: 'Eliminar jornada',
  workingTimeSectionAddSubmitAction: 'Añadir jornada',
  workingTimeSectionCorrectSubmitAction: 'Guardar corrección',
  workingTimeSectionRemoveSubmitAction: 'Eliminar jornada',
  workingTimeSectionStartDateAriaLabel: 'Fecha inicio de la jornada',
  workingTimeSectionEndDateAriaLabel: 'Fecha fin de la jornada (vacía si queda en vigor)',
  workingTimeSectionPercentageAriaLabel: 'Porcentaje de jornada',
  workingTimeSectionPlanningMessage: 'Calculando qué cambiaría…',
  workingTimeSectionCoverageGapMessage:
    'La jornada dejaría sin cubrir un tramo de la presencia del empleado.',
  periodCascadeWarningMessage:
    'La fecha de inicio del período anterior se ajustará automáticamente.',
  laborClassificationBlockTitle: 'Clasificación laboral',
  laborClassificationBlockCurrentLabel: 'Clasificación actual',
  laborClassificationBlockCurrentActiveSectionLabel: 'Clasificación activa',
  laborClassificationBlockCurrentSectionLabel: 'Clasificación actual',
  laborClassificationBlockCurrentActiveLabel: 'Clasificación activa actual.',
  laborClassificationBlockCurrentActiveMostRecentLabel:
    'Hay varias clasificaciones activas; se muestra la más reciente.',
  laborClassificationBlockCurrentLatestClosedLabel:
    'No hay clasificación activa; se muestra la última clasificación registrada.',
  laborClassificationBlockHistoryTitle: 'Historial de clasificaciones',
  laborClassificationBlockHistoryEmptyMessage: 'Sin períodos anteriores registrados.',
  laborClassificationBlockEmptyMessage: 'No hay clasificaciones laborales disponibles.',
  laborClassificationLoadFailedMessage:
    'No se pudo cargar la información de clasificación laboral.',
  laborClassificationBlockStatusActive: 'Activa',
  laborClassificationBlockStatusClosed: 'Cerrada',
  laborClassificationBlockPeriodLabel: 'Período',
  laborClassificationBlockOpenPeriodLabel: 'actual',
  laborClassificationBlockAgreementLabel: 'Convenio',
  laborClassificationBlockCategoryLabel: 'Categoría',
  laborClassificationSectionTitle: 'Clasificación laboral',
  laborClassificationSectionSubtitle: 'Gestiona la clasificación laboral vigente y su histórico.',
  laborClassificationSectionManageAction: 'Cambiar clasificación desde fecha',
  laborClassificationSectionExitManageAction: 'Salir',
  laborClassificationSectionReplaceAction: 'Cambiar clasificación desde fecha',
  laborClassificationSectionCorrectAction: 'Corregir ocurrencia',
  laborClassificationSectionCloseAction: 'Cerrar',
  laborClassificationSectionDeleteAction: 'Eliminar',
  laborClassificationSectionCancelAction: 'Cancelar',
  laborClassificationSectionSaveReplaceAction: 'Guardar reemplazo',
  laborClassificationSectionSaveCorrectAction: 'Guardar corrección',
  laborClassificationSectionConfirmCloseMessage:
    'Confirma el cierre de esta ocurrencia de clasificación laboral.',
  laborClassificationSectionConfirmCloseAction: 'Confirmar cierre',
  laborClassificationSectionConfirmDeleteMessage:
    'La eliminación no esta habilitada para clasificación laboral.',
  laborClassificationSectionConfirmDeleteAction: 'Confirmar eliminación',
  laborClassificationSectionEmptyMessage: 'No hay clasificaciones laborales cargadas.',
  laborClassificationSectionStatusActive: 'Vigente',
  laborClassificationSectionStatusClosed: 'Histórica',
  laborClassificationSectionCurrentPeriodLabel: 'actual',
  laborClassificationSectionPeriodPrefix: 'Período',
  laborClassificationSectionCategoryPrefix: 'Categoría',
  laborClassificationSectionReplaceHint:
    'El reemplazo crea una nueva ocurrencia desde la fecha efectiva y ajusta la vigencia anterior según reglas del backend.',
  laborClassificationSectionEffectiveDateLabel: 'Fecha efectiva',
  laborClassificationSectionAgreementLabel: 'Convenio',
  laborClassificationSectionSelectAgreementPlaceholder: 'Selecciona un convenio',
  laborClassificationSectionAgreementPlaceholder: 'Código de convenio',
  laborClassificationSectionCategoryLabel: 'Categoría',
  laborClassificationSectionSelectCategoryPlaceholder: 'Selecciona una categoría',
  laborClassificationSectionCategoryPlaceholder: 'Código de categoría',
  laborClassificationSectionLookupPendingHint:
    'La selección asistida de convenio y categoría llegara cuando esten disponibles las maestras.',
  laborClassificationSectionOccurrenceStartDateLabel: 'Inicio',
  laborClassificationSectionCorrectHint:
    'La corrección actualiza la ocurrencia seleccionada manteniendo su fecha de inicio original.',
  laborClassificationSectionCloseHint:
    'Indica la fecha de cierre para finalizar la ocurrencia vigente sin eliminar historial.',
  laborClassificationSectionCloseDateLabel: 'Fecha de cierre',
  laborClassificationSectionInvalidDataMessage:
    'Completa los datos obligatorios para continuar con la operación.',
  laborClassificationSectionCloseDateInvalidMessage:
    'La fecha de cierre debe ser igual o posterior al inicio de la ocurrencia.',
  laborClassificationSectionOverlapMessage:
    'La clasificación se solapa con otra ocurrencia vigente o histórica del empleado.',
  laborClassificationSectionOutsidePresenceMessage:
    'La clasificación debe quedar dentro de un período de presencia del empleado.',
  laborClassificationSectionIncompleteCoverageMessage:
    'La operación deja un hueco temporal no permitido en la cobertura de clasificación laboral.',
  laborClassificationSectionInvalidPeriodMessage:
    'El período informado no es válido para esta operación de clasificación laboral.',
  laborClassificationSectionAlreadyClosedMessage:
    'La ocurrencia ya esta cerrada y no admite un nuevo cierre.',
  laborClassificationSectionNotFoundMessage:
    'No se encontro la ocurrencia seleccionada de clasificación laboral.',
  laborClassificationSectionAgreementNotFoundMessage:
    'El convenio indicado no existe para el sistema de reglas activo.',
  laborClassificationSectionAgreementCategoryNotFoundMessage:
    'La categoría indicada no existe para el sistema de reglas activo.',
  laborClassificationSectionAgreementCategoryRelationInvalidMessage:
    'La categoría no pertenece al convenio seleccionado para esta fecha efectiva.',
  laborClassificationSectionRequestFailedMessage:
    'No se pudo procesar la operación de clasificación laboral. Reintenta.',
  laborClassificationSectionCatalogRequestFailedMessage:
    'No se pudo cargar el catalogo de convenios y categorías. Reintenta.',
  laborClassificationSectionReplaceSuccessMessage: 'Clasificación reemplazada correctamente.',
  laborClassificationSectionCorrectSuccessMessage: 'Clasificación corregida correctamente.',
  laborClassificationSectionCloseSuccessMessage: 'Clasificación cerrada correctamente.',
  laborFutureBlockTitle: 'Evolucion laboral',
  laborFutureBlockDescription:
    'Preparado para eventos de movilidad, cambios de categoría y transiciones de jornada.',
  currentEmployeeKeyLabel: 'Employee business key',
  currentEmployeeLabel: 'Employee number',
  placeholderMessage: 'This section is intentionally minimal and ready for OpenAPI integration.',
  hireEmployeeTitle: 'Nueva contratación',
  hireEmployeeSubtitle:
    'Inicia el ciclo de vida de un nuevo empleado en el sistema de reglas seleccionado.',
  hireEmployeeIdentitySectionTitle: 'Identidad del empleado',
  hireEmployeeHiringSectionTitle: 'Datos de contratación',
  hireEmployeeOrganizationSectionTitle: 'Contexto organizativo inicial',
  hireEmployeeLaborSectionTitle: 'Contexto laboral inicial',
  hireEmployeeAction: 'Contratar empleado',
  hireEmployeeCancelAction: 'Cancelar',
  hireEmployeeSuccessMessage: 'Empleado contratado correctamente.',
  hireEmployeeErrorMessage: 'No se pudo completar la contratación. Reintenta.',
  hireEmployeeConflictMessage: 'El empleado ya existe en el sistema.',
  hireEmployeeInvalidCatalogMessage:
    'Uno o más valores de catálogo son inválidos para la fecha seleccionada.',
  hireEmployeeWorkingTimeTitle: 'Jornada inicial',
  hireEmployeeWorkingTimeHint: 'Las horas se calculan automáticamente a partir del porcentaje.',
  hireEmployeeWorkingTimeRequiredMessage: 'Indica el porcentaje de jornada inicial.',
  hireEmployeeWorkingTimeRangeMessage:
    'El porcentaje de jornada debe ser mayor que 0 y menor o igual que 100.',
  hireEmployeeSummaryTitle: 'Resultado de la contratación',
  hireEmployeeSummaryEmployeeLabel: 'Empleado',
  hireEmployeeSummaryStatusLabel: 'Estado',
  hireEmployeeSummaryHireDateLabel: 'Fecha de alta',
  hireEmployeeSummaryWorkingTimeTitle: 'Jornada creada',
  hireEmployeeSummarySincePrefix: 'Desde',
  rehireEmployeeTitle: 'Recontratar empleado',
  rehireEmployeeSubtitle: 'Reapertura del ciclo laboral para un empleado existente.',
  rehireEmployeeDataSectionTitle: 'Datos de reincorporación',
  rehireEmployeeOrganizationSectionTitle: 'Contexto organizativo inicial',
  rehireEmployeeLaborSectionTitle: 'Contexto laboral inicial',
  rehireEmployeeAction: 'Recontratar empleado',
  rehireEmployeeCancelAction: 'Cancelar',
  rehireEmployeeSuccessMessage: 'Empleado recontratado correctamente.',
  rehireEmployeeNotFoundMessage: 'No se encontró el empleado o el sistema.',
  rehireEmployeeAlreadyActiveMessage: 'El empleado ya está activo.',
  rehireEmployeeInvalidDateMessage: 'La fecha de reincorporación no es válida.',
  rehireEmployeeConflictMessage:
    'La reincorporación entra en conflicto con el estado actual del empleado.',
  rehireEmployeeInvalidWorkingTimeMessage:
    'La jornada inicial no es válida para la reincorporación.',
  rehireEmployeeInvalidDistributionMessage: 'La distribución de centros de coste no es válida.',
  rehireEmployeeInvalidDependentRelationMessage:
    'Existe una relación dependiente no válida para la reincorporación.',
  rehireEmployeeInvalidCatalogMessage:
    'Uno o más valores de catálogo son inválidos para la fecha seleccionada.',
  rehireEmployeeRequestFailedMessage: 'No se pudo completar la reincorporación. Reintenta.',
  rehireEmployeeMissingKeyRouteMessage: 'Falta la clave del empleado en la ruta.',
  rehireEmployeeMissingKeyMessage: 'Falta la clave del empleado.',
  rehireEmployeeWorkingTimeTitle: 'Porcentaje de jornada',
  rehireEmployeeWorkingTimeHint: 'Las horas se calculan automáticamente a partir del porcentaje.',
  rehireEmployeeWorkingTimeRequiredMessage: 'Indica el porcentaje de jornada inicial.',
  rehireEmployeeWorkingTimeRangeMessage:
    'El porcentaje de jornada debe ser mayor que 0 y menor o igual que 100.',
  rehireEmployeeSummaryTitle: 'Resultado de la reincorporación',
  rehireEmployeeSummaryEmployeeLabel: 'Empleado',
  rehireEmployeeSummaryStatusLabel: 'Estado',
  rehireEmployeeSummaryDateLabel: 'Fecha de reincorporación',
  rehireEmployeeSummaryWorkingTimeTitle: 'Nueva jornada',
  rehireEmployeeSummarySincePrefix: 'Desde',
  employeeConvenioLabel: 'Convenio',
  employeeTypeLabel: 'Tipo',
  employeeNumberLabel: 'Número',
  employeeFechaAltaLabel: 'Fecha alta',
  employeeNameColumnLabel: 'Nombre',
  employeeClaveColumnLabel: 'Clave',
  employeeWorkCenterColumnLabel: 'Centro',
  directoryNoWorkCenterLabel: 'Sin centro',
  directoryStatusFilterLabel: 'Estado',
  directoryStatusAllLabel: 'Todos',
  directoryStatusActiveLabel: 'Activos',
  directoryStatusTerminatedLabel: 'De baja',
  directoryCountEmployeesSuffix: 'empleados',
  directoryCountMatchesSuffix: 'coincidencias',
  directoryCountOneEmployee: '1 empleado',
  directoryCountOneMatch: '1 coincidencia',
  detailNavAriaLabel: 'Secciones del empleado',
  workQueueTitle: 'Cola de trabajo',
  workQueuePositionOf: 'de',
  workQueueCriteriaAll: 'todos',
  workQueueCriteriaActive: 'activos',
  workQueueCriteriaTerminated: 'de baja',
  workQueuePreviousAction: 'Anterior',
  workQueueNextAction: 'Siguiente',
  workQueueKeysHint: 'K anterior · J siguiente',
  workQueueBackToListAction: 'Volver a la lista',
  workQueueLeaveAction: 'Salir de la cola',
  workQueueEndMessage: 'Fin de la cola.',
  workQueueStartMessage: 'Es el primero de la cola.',
  workQueueMovedMessage:
    'La cola ha cambiado mientras la recorrías: alguien ha modificado datos. Sigues sobre lo que hay ahora.',
  workQueueEmptyMessage: 'Ya no hay nadie que cumpla el criterio de la cola.',
  workQueueFailedMessage: 'No se pudo pedir el siguiente de la cola. Reintenta.',
  directoryTraverseAction: 'Recorrer',
  directoryQueueContinueAction: 'Continuar',
  directoryQueueLeaveAction: 'Salir',
} as const;
