export const workCenterTexts = {
  pageTitle: 'Centros de trabajo',
  pageSubtitle: '',
  newWorkCenterAction: 'Nuevo centro',

  listTitle: 'Centros',
  listSubtitle: '',
  listSearchPlaceholder: 'Buscar por código, nombre, empresa o ubicación',
  listLoadFailedMessage: 'No se pudo cargar el listado de centros.',
  listEmptyMessage: 'No hay centros de trabajo registrados.',

  listMetaCompanyLabel: 'Empresa',
  listMetaLocationLabel: 'Ubicación',
  listMetaStartDateLabel: 'Inicio',

  activeLabel: 'Vigente',
  inactiveLabel: 'Histórico',
  draftLabel: 'Borrador',

  detailPanelTitle: 'Ficha de centro',
  detailLoadingMessage: 'Cargando detalle... ',
  detailLoadFailedMessage: 'No se pudo cargar el detalle del centro.',
  detailNotFoundMessage: 'No se encontró el centro seleccionado.',
  emptyDetailDescription: 'Selecciona un centro o crea uno nuevo.',

  formCreateTitle: 'Nuevo centro',
  formEditTitle: 'Editar centro',
  formViewTitle: 'Detalle de centro',
  formSaveAction: 'Guardar',
  formCancelAction: 'Cancelar',
  formEditAction: 'Editar',

  detailHeaderCodeLabel: 'Código',
  detailHeaderCompanyLabel: 'Empresa',
  detailHeaderLocationLabel: 'Ubicación',
  detailViewEmptyValue: '—',
  detailDescriptionEmpty: 'Sin descripción',
  detailAddressEmpty: 'Sin dirección informada.',

  sectionIdentityTitle: 'Identificación',
  sectionAddressTitle: 'Dirección',
  sectionContactsTitle: 'Contactos',

  fieldRuleSystemCodeLabel: 'Sistema de reglas',
  fieldWorkCenterCodeLabel: 'Código centro',
  fieldNameLabel: 'Nombre',
  fieldDescriptionLabel: 'Descripción',
  fieldStartDateLabel: 'Fecha inicio',
  fieldCompanyCodeLabel: 'Empresa',
  fieldStreetLabel: 'Dirección',
  fieldCityLabel: 'Ciudad',
  fieldPostalCodeLabel: 'Código postal',
  fieldRegionCodeLabel: 'Provincia',
  fieldCountryCodeLabel: 'País',

  contactsLoadingMessage: 'Cargando contactos... ',
  contactsLoadFailedMessage: 'No se pudieron cargar los contactos.',
  contactsEmptyMessage: 'No hay contactos registrados para este centro.',
  contactsCreateHint: 'Guarda el centro para poder gestionar contactos.',
  contactsNewAction: 'Nuevo contacto',
  contactsEditAction: 'Editar',
  contactsDeleteAction: 'Borrar',
  contactsSaveAction: 'Guardar contacto',
  contactsCancelAction: 'Cancelar',
  contactsTypeLabel: 'Tipo',
  contactsTypePlaceholder: 'Selecciona un tipo',
  contactsValueLabel: 'Valor',
  contactsNumberLabel: 'N.º',
  contactsCreateTitle: 'Nuevo contacto',
  contactsEditTitle: 'Editar contacto',
  contactsCatalogLoadingMessage: 'Cargando tipos de contacto... ',
  contactsCatalogLoadFailedMessage: 'No se pudieron cargar los tipos de contacto.',
  contactsCatalogEmptyMessage: 'No hay tipos de contacto disponibles para este centro.',
  contactsSubmitSuccessCreated: 'Contacto creado correctamente.',
  contactsSubmitSuccessUpdated: 'Contacto actualizado correctamente.',
  contactsSubmitSuccessDeleted: 'Contacto eliminado correctamente.',

  submitSuccessCreated: 'Centro creado correctamente.',
  submitSuccessUpdated: 'Centro actualizado correctamente.',
};
